kind: Service
apiVersion: v1
metadata:
  name: poi-service
  namespace: api
  labels:
    app: poi
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: poi
  type: ClusterIP
