kind: Service
apiVersion: v1
metadata:
  name: tripsapi-service
  namespace: api
  labels:
    app: tripsapi
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: tripsapi
  type: ClusterIP
