kind: Service
apiVersion: v1
metadata:
  name: userapi-service
  namespace: api
  labels:
    app: userapi
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: userapi
  type: ClusterIP
