kind: Deployment
apiVersion: apps/v1
metadata:
  name: poi
  namespace: api
  labels:
    app: poi
  annotations:
    deployment.kubernetes.io/revision: '2'
spec:
  replicas: 3
  selector:
    matchLabels:
      app: poi
  template:
    metadata:
      labels:
        app: poi
    spec:
      volumes:
        - name: sqlconnection
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: team2-kv-secrets
      containers:
        - name: poi
          image: registrytzm1400.azurecr.io/poi:1.0
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: WEB_PORT
              value: '8080'
            - name: WEB_SERVER_BASE_URI
              value: http://poi-service.api.svc.cluster.local:8080
            - name: CONFIG_FILES_PATH
              value: /secrets
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
          resources: {}
          volumeMounts:
            - name: sqlconnection
              readOnly: true
              mountPath: /secrets
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
