apiVersion: apps/v1
kind: Deployment
metadata:
  name: tripviewer
  namespace: web
  labels:
    app: tripviewer
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tripviewer
  template:
    metadata:
      labels:
        app: tripviewer
    spec:
      containers:
      - image: registrytzm1400.azurecr.io/tripviewer:1.0
        env:
        - name: USERPROFILE_API_ENDPOINT
          value: "http://userprofile-service:80"
        - name: TRIPS_API_ENDPOINT
          value: "http://tripsapi-service:80"
        name: tripviewer
        ports:
        - containerPort: 80
        resources: {}
      dnsPolicy: ClusterFirst
      restartPolicy: Always