kind: Deployment
apiVersion: apps/v1
metadata:
  name: tripviewer
  namespace: web
  labels:
    app: tripviewer
  annotations:
    deployment.kubernetes.io/revision: '1'
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tripviewer
  template:
    metadata:
      labels:
        app: tripviewer
    spec:
      containers:
        - name: tripviewer
          image: registrytzm1400.azurecr.io/tripviewer:1.0
          ports:
            - containerPort: 80
              protocol: TCP
          env:
            - name: USERPROFILE_API_ENDPOINT
              value: http://userprofile-service.api.svc.cluster.local:80
            - name: TRIPS_API_ENDPOINT
              value: http://tripsapi-service.api.svc.cluster.local:80
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
