kind: Deployment
apiVersion: apps/v1
metadata:
  name: userprofile
  namespace: api
  labels:
    app: userprofile
  annotations:
    deployment.kubernetes.io/revision: '2'
spec:
  replicas: 3
  selector:
    matchLabels:
      app: userprofile
  template:
    metadata:
      labels:
        app: userprofile
    spec:
      volumes:
        - name: sqlconnection
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: team2-kv-secrets
      containers:
        - name: userprofile
          image: registrytzm1400.azurecr.io/userprofile:1.0
          ports:
            - containerPort: 80
              protocol: TCP
          env:
            - name: PORT
              value: '80'
          resources: {}
          volumeMounts:
            - name: sqlconnection
              readOnly: true
              mountPath: /secrets
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
