apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: web
  name: webdev-edit
subjects:
- kind: Group
  name: cf472348-04c0-4ea3-9a8e-2dd76c2350c2
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole 
  name: edit
  apiGroup: rbac.authorization.k8s.io